apiVersion: v1
kind: Service
metadata:
  name: python-nodeport-svc
  namespace: dev-test
spec:
  type: NodePort
  selector:
    app: python-app   # must match pod label
  ports:
  - port: 5000        # service port
    targetPort: 5000  # container port
    nodePort: 30081   # external port on the node
