apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: dev-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: amit653/my-python-app:latest
        imagePullPolicy: Always  #ensures it always pulls from Docker Hub
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        ports:
        - containerPort: 5000 #  app port
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
