apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: dev-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  #pod label
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: student
    ## add readiness probe The Postgres pod starts, but until it passes the readiness probe, it’s marked NotReady & service endpoint will be empty
        ports:
        - containerPort: 5432
        readinessProbe:        # readiness probe
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
