name: CI manifest check
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: dry run
        working-directory: /home/vagrant/python-pg-connection
        run: |
          kubectl apply --dry-run=server -f k8s/db.yml -n dev-test
          kubectl apply --dry-run=server -f k8s/pg-svc.yml -n dev-test
          kubectl apply --dry-run=server -f k8s/app-nodeport-svc.yml -n dev-test
          kubectl apply --dry-run=server -f k8s/app.yml -n dev-test
          kubectl apply --dry-run=server -f k8s/app-svc.yml -n dev-test
